### ISSUE TITLE
Failed to compile on Windows

### ISSUE THREAD

**Issue by valentinmk** [igorcoding/asynctnt#1] opened 2017-09-07 08:26 UTC
I am on Windows 10 with Windows SDK 10.0.10240.0 installed.
After `pip install asynctnt` everything going fine until:
`creating build\temp.win-amd64-3.6\Release\third_party\msgpuck`
Than I got this error in console:

```
 C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I-Ithird_party "-Ic:\program files\python36\include" "-Ic:\program files\python36\include" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\winrt" /Tcasynctnt/iproto/protocol.c /Fobuild\temp.win-amd64-3.6\Release\asynctnt/iproto/protocol.obj
    protocol.c
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(174): error C2061: syntax error: identifier '__attribute__'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(174): error C2059: syntax error: ';'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(235): error C2079: 'packed' uses undefined struct '__attribute__'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(235): error C2146: syntax error: missing ';' before identifier 'cast'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(235): error C2065: 'cast': undeclared identifier
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(235): error C2143: syntax error: missing ';' before '{'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(235): error C2037: left of 'val' specifies undefined struct/union 'cast'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(239): error C2079: 'packed' uses undefined struct '__attribute__'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(239): error C2146: syntax error: missing ';' before identifier 'cast'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(239): error C2065: 'cast': undeclared identifier
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(239): error C2143: syntax error: missing ';' before '{'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(239): error C2037: left of 'val' specifies undefined struct/union 'cast'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(240): error C2079: 'packed' uses undefined struct '__attribute__'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(240): error C2146: syntax error: missing ';' before identifier 'cast'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(240): error C2065: 'cast': undeclared identifier
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(240): error C2143: syntax error: missing ';' before '{'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(240): error C2037: left of 'val' specifies undefined struct/union 'cast'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(241): error C2079: 'packed' uses undefined struct '__attribute__'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(241): error C2146: syntax error: missing ';' before identifier 'cast'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(241): error C2065: 'cast': undeclared identifier
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(241): error C2143: syntax error: missing ';' before '{'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(241): error C2037: left of 'val' specifies undefined struct/union 'cast'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(266): error C2061: syntax error: identifier 'mp_float_cast'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(266): error C2059: syntax error: ';'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(266): error C2449: found '{' at file scope (missing function header?)
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(269): error C2059: syntax error: '}'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(288): error C2079: 'cast' uses undefined union 'mp_float_cast'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(290): error C2224: left of '.u32' must have struct/union type
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(291): error C2224: left of '.f' must have struct/union type
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(291): warning C4033: 'mp_load_float' must return a value
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(288): error C2440: 'initializing': cannot convert from 'mp_float_cast' to 'int'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(297): error C2079: 'cast' uses undefined union 'mp_double_cast'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(299): error C2224: left of '.u64' must have struct/union type
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(300): error C2224: left of '.d' must have struct/union type
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(300): warning C4033: 'mp_load_double' must return a value
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(297): error C2440: 'initializing': cannot convert from 'mp_double_cast' to 'int'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(306): error C2079: 'cast' uses undefined union 'mp_float_cast'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(307): error C2224: left of '.f' must have struct/union type
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(308): error C2224: left of '.u32' must have struct/union type
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(309): error C2440: '=': cannot convert from 'int' to 'mp_float_cast'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(316): error C2079: 'cast' uses undefined union 'mp_double_cast'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(317): error C2224: left of '.d' must have struct/union type
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(318): error C2224: left of '.u64' must have struct/union type
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(319): error C2440: '=': cannot convert from 'int' to 'mp_double_cast'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(373): error C2143: syntax error: missing ')' before '('
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(373): error C2059: syntax error: ')'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(374): error C2143: syntax error: missing ')' before 'type'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(374): error C2091: function returns function
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(374): error C2085: 'mp_typeof': not in formal parameter list
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(383): error C2143: syntax error: missing ')' before '('
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(383): error C2059: syntax error: ')'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(384): error C2146: syntax error: missing ')' before identifier 'mp_sizeof_array'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(384): error C2091: function returns function
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(384): error C2082: redefinition of formal parameter '__attribute__'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(384): error C2146: syntax error: missing ',' before identifier 'mp_sizeof_array'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(384): error C2143: syntax error: missing ';' before '('
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(384): error C2059: syntax error: ')'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(426): error C2143: syntax error: missing ')' before '('
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(426): error C2059: syntax error: ')'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(426): error C2146: syntax error: missing ')' before identifier 'ptrdiff_t'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(426): error C2091: function returns function
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(427): error C2085: 'mp_check_array': not in formal parameter list
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(439): error C2085: 'mp_decode_array': not in formal parameter list
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(448): error C2143: syntax error: missing ')' before '('
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(448): error C2059: syntax error: ')'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(449): error C2146: syntax error: missing ')' before identifier 'mp_sizeof_map'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(449): error C2091: function returns function
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(449): error C2082: redefinition of formal parameter '__attribute__'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(449): error C2146: syntax error: missing ',' before identifier 'mp_sizeof_map'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(449): error C2143: syntax error: missing ';' before '('
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(449): error C2059: syntax error: ')'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(497): error C2143: syntax error: missing ')' before '('
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(497): error C2059: syntax error: ')'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(497): error C2146: syntax error: missing ')' before identifier 'ptrdiff_t'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(497): error C2091: function returns function
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(498): error C2085: 'mp_check_map': not in formal parameter list
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(510): error C2085: 'mp_decode_map': not in formal parameter list
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(527): error C2143: syntax error: missing ')' before '('
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(527): error C2059: syntax error: ')'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(528): error C2146: syntax error: missing ')' before identifier 'mp_sizeof_uint'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(528): error C2091: function returns function
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(528): error C2082: redefinition of formal parameter '__attribute__'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(528): error C2146: syntax error: missing ',' before identifier 'mp_sizeof_uint'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(528): error C2143: syntax error: missing ';' before '('
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(528): error C2059: syntax error: ')'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(538): error C2143: syntax error: missing ')' before '('
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(538): error C2059: syntax error: ')'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(539): error C2146: syntax error: missing ')' before identifier 'mp_sizeof_int'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(539): error C2091: function returns function
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(539): error C2061: syntax error: identifier 'mp_sizeof_int'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(539): error C2059: syntax error: ';'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(539): error C2059: syntax error: '<parameter-list>'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(575): error C2143: syntax error: missing ')' before '('
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(575): error C2059: syntax error: ')'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(575): error C2146: syntax error: missing ')' before identifier 'ptrdiff_t'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(575): error C2091: function returns function
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(576): error C2085: 'mp_check_uint': not in formal parameter list
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(587): error C2143: syntax error: missing ')' before '('
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(587): error C2059: syntax error: ')'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(587): error C2146: syntax error: missing ')' before identifier 'ptrdiff_t'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(587): error C2091: function returns function
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(587): error C2082: redefinition of formal parameter '__attribute__'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(587): error C2146: syntax error: missing ',' before identifier 'ptrdiff_t'
    c:\users\valentinmk\appdata\local\temp\pip-build-b_fc1cix\asynctnt\asynctnt\iproto\../../third_party/msgpuck/msgpuck.h(587): fatal error C1003: error count exceeds 100; stopping compilation
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
```

**Comment by Skorpyon** [comment] 2017-10-23 19:58
> Failed to compile on Windows

It is not a bug, but it is a feature )))

**Comment by valentinmk** [comment] 2017-10-23 20:25
> It is not a bug, but it is a feature )))

I don't want to run asynctnt on Windows. I need a code highlighting and hints in a VS Code for asynctnt and asynctnt-queue libraries.

**Comment by igorcoding** [comment] 2017-10-23 23:16
The problem is that https://github.com/tarantool/msgpuck cannot be compiled on Windows. I've been trying to look at this issue but it seems like a lot of effort needed to be able to compile it.

**Comment by valentinmk** [comment] 2017-10-26 11:24
So, i think we could close this issue.
I solve an code completition and hints problem.
I copy an asynctnt folder from last realese to <Path to Python>\Lib\site-packages and VS Code work just fine for me.

**Comment by habelmic** [comment] 2018-08-08 13:57
Is there really no way to compile the library on Windows? I am developing on Windows though my production environment will be on Ubuntu and I'd prefer if I could test things locally instead of having to create a remote deployment just to test my app.

**Comment by igorcoding** [comment] 2018-08-09 08:41
asynctnt is easily compiled using Windows subsystem for Linux, and there is a possibility to integrate IDE with the remote python in Linux, e.g. https://www.jetbrains.com/help/pycharm/using-wsl-as-a-remote-interpreter.html for PyCharm. Maybe you can have a look at this?
Moreover, Tarantool itself cannot be run under Windows as far as I know - only in WSL.

**Comment by habelmic** [comment] 2018-08-10 07:12
That does help, thank you. Unfortunately, I'm on Windows 7 and upgrading to Win 10 is not a possibility.
However,  I was able to work around the issue by setting a remote interpreter via SSH in PyCharm to my Ubuntu server and that works.
Thanks for the help.

**Comment by igorcoding** [comment] 2020-01-12 20:20
Hi @habelmic @valentinmk 
In case you still interested - starting from `asynctnt==1.1` enabled building Windows wheels for Python 3.6, 3.7 and 3.8, so `asynctnt` can be installed right in the Windows environment.
I guess can close this issue now :)

**Closed by igorcoding** 2020-01-12 20:20 UTC
